name: AutoSync Server
on: [push]
jobs:
  build:
    name: sync
    runs-on: ubuntu-latest
    steps:
    - name: connect
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/discord-bot && bash start.sh
